services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Moscow
    restart: always
    ports:
      - 8001:8000
    command: >
      sh -c ' 
        python -m alembic upgrade head &&
        python -m fastapi run main.py --host 0.0.0.0 --port 8000
      '
    depends_on:
      db:
        condition: service_healthy
    networks:
      - probook-network

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - probook-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "probook"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "54svrdtyf"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - probook-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    environment:
      - TZ=Europe/Moscow
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "save 30 1" >> /usr/local/etc/redis/redis.conf &&
        echo "notify-keyspace-events Ex" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    restart: always
    networks:
      - probook-network

volumes:
  probook-db-data:


networks:
  probook-network:
    name: probook-network
    external: false
