"""change personal_reservation

Revision ID: 0faf0faf5bb2
Revises: d63ff8b474b7
Create Date: 2025-02-22 09:16:08.542545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0faf0faf5bb2'
down_revision: Union[str, None] = 'd63ff8b474b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_reservation', sa.Column('date_start', sa.TIMESTAMP(), nullable=False))
    op.add_column('personal_reservation', sa.Column('date_end', sa.TIMESTAMP(), nullable=False))
    op.drop_column('personal_reservation', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_reservation', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('personal_reservation', 'date_end')
    op.drop_column('personal_reservation', 'date_start')
    # ### end Alembic commands ###
