"""empty message

Revision ID: 1ae2ead4d3a3
Revises: 69828e797c84
Create Date: 2024-11-28 21:43:52.160446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae2ead4d3a3'
down_revision: Union[str, None] = '69828e797c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('info_for_moderator', sa.TEXT(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('participants', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('repeat', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('moderated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('info_for_moderator', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('moderated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('personal_reservation')
    op.drop_table('event')
    op.drop_table('room')
    # ### end Alembic commands ###