"""empty message

Revision ID: 747370f977f4
Revises: a58ee7d35d81
Create Date: 2024-12-08 19:54:45.376472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747370f977f4'
down_revision: Union[str, None] = 'a58ee7d35d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('needable_items', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('personal_reservation', sa.Column('needable_items', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_reservation', 'needable_items')
    op.drop_column('event', 'needable_items')
    op.drop_table('item')
    # ### end Alembic commands ###
