"""empty message

Revision ID: 9724fbab65e3
Revises: a61be244bc71
Create Date: 2024-11-29 17:47:01.193362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9724fbab65e3'
down_revision: Union[str, None] = 'a61be244bc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_start', sa.TIMESTAMP(), nullable=False))
    op.add_column('event', sa.Column('date_end', sa.TIMESTAMP(), nullable=False))
    op.drop_column('event', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'date_end')
    op.drop_column('event', 'date_start')
    # ### end Alembic commands ###
