"""indexes added

Revision ID: 97b1e68724f5
Revises: e9758e875a1c
Create Date: 2025-05-08 13:13:03.946912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b1e68724f5'
down_revision: Union[str, None] = 'e9758e875a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_action_history_action'), 'action_history', ['action'], unique=False)
    op.create_index(op.f('ix_action_history_date'), 'action_history', ['date'], unique=False)
    op.create_index(op.f('ix_event_date_end'), 'event', ['date_end'], unique=False)
    op.create_index(op.f('ix_event_date_start'), 'event', ['date_start'], unique=False)
    op.create_index(op.f('ix_event_img'), 'event', ['img'], unique=False)
    op.create_index(op.f('ix_event_repeat'), 'event', ['repeat'], unique=False)
    op.create_index(op.f('ix_event_room_id'), 'event', ['room_id'], unique=False)
    op.create_index(op.f('ix_event_status'), 'event', ['status'], unique=False)
    op.create_index(op.f('ix_event_user_uuid'), 'event', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_item_room_id'), 'item', ['room_id'], unique=False)
    op.create_index(op.f('ix_personal_reservation_date_end'), 'personal_reservation', ['date_end'], unique=False)
    op.create_index(op.f('ix_personal_reservation_date_start'), 'personal_reservation', ['date_start'], unique=False)
    op.create_index(op.f('ix_personal_reservation_room_id'), 'personal_reservation', ['room_id'], unique=False)
    op.create_index(op.f('ix_personal_reservation_status'), 'personal_reservation', ['status'], unique=False)
    op.create_index(op.f('ix_personal_reservation_user_uuid'), 'personal_reservation', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_room_img'), 'room', ['img'], unique=False)
    op.create_index(op.f('ix_schedule_date'), 'schedule', ['date'], unique=False)
    op.create_index(op.f('ix_schedule_room_id'), 'schedule', ['room_id'], unique=False)
    op.create_index(op.f('ix_user_group_id'), 'user', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_group_id'), table_name='user')
    op.drop_index(op.f('ix_schedule_room_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_date'), table_name='schedule')
    op.drop_index(op.f('ix_room_img'), table_name='room')
    op.drop_index(op.f('ix_personal_reservation_user_uuid'), table_name='personal_reservation')
    op.drop_index(op.f('ix_personal_reservation_status'), table_name='personal_reservation')
    op.drop_index(op.f('ix_personal_reservation_room_id'), table_name='personal_reservation')
    op.drop_index(op.f('ix_personal_reservation_date_start'), table_name='personal_reservation')
    op.drop_index(op.f('ix_personal_reservation_date_end'), table_name='personal_reservation')
    op.drop_index(op.f('ix_item_room_id'), table_name='item')
    op.drop_index(op.f('ix_event_user_uuid'), table_name='event')
    op.drop_index(op.f('ix_event_status'), table_name='event')
    op.drop_index(op.f('ix_event_room_id'), table_name='event')
    op.drop_index(op.f('ix_event_repeat'), table_name='event')
    op.drop_index(op.f('ix_event_img'), table_name='event')
    op.drop_index(op.f('ix_event_date_start'), table_name='event')
    op.drop_index(op.f('ix_event_date_end'), table_name='event')
    op.drop_index(op.f('ix_action_history_date'), table_name='action_history')
    op.drop_index(op.f('ix_action_history_action'), table_name='action_history')
    # ### end Alembic commands ###
