"""event base id

Revision ID: c1dfee668d3e
Revises: edaa8e9ee78d
Create Date: 2025-04-03 15:09:37.806769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1dfee668d3e'
down_revision: Union[str, None] = 'edaa8e9ee78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE event_base_id_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_base_id', sa.Integer(), server_default=sa.text("nextval('event_base_id_seq')"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_base_id')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE event_base_id_seq")
