"""room_img

Revision ID: e9758e875a1c
Revises: c1dfee668d3e
Create Date: 2025-05-04 17:30:46.237181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9758e875a1c'
down_revision: Union[str, None] = 'c1dfee668d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'img')
    # ### end Alembic commands ###
