"""room_description_and_item_room_id

Revision ID: eb49f84f5578
Revises: b607e3d06065
Create Date: 2025-03-14 12:40:36.778545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb49f84f5578'
down_revision: Union[str, None] = 'b607e3d06065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'room', ['room_id'], ['id'])
    op.add_column('room', sa.Column('description', sa.TEXT(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'description')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'room_id')
    # ### end Alembic commands ###
