"""application states

Revision ID: edaa8e9ee78d
Revises: 183d81ea33f2
Create Date: 2025-04-03 14:13:07.287708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edaa8e9ee78d'
down_revision: Union[str, None] = '183d81ea33f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.SMALLINT(), server_default='0', nullable=False))
    op.drop_column('event', 'moderated')
    op.add_column('personal_reservation', sa.Column('status', sa.SMALLINT(), server_default='0', nullable=False))
    op.drop_column('personal_reservation', 'moderated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_reservation', sa.Column('moderated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('personal_reservation', 'status')
    op.add_column('event', sa.Column('moderated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
